services:
  - type: web
    name: study-analyzer
    env: java
    region: oregon
    plan: free
    rootDir: project_1
    buildCommand: |
      javac -cp "lib/*" Main.java
      jar cvfm study-analyzer.jar MANIFEST.MF *.jsp WEB-INF Main.class
    startCommand: |
      java -cp "study-analyzer.jar:lib/*" Main
    healthCheckPath: /login.jsp
    envVars:
      - key: DB_HOST
        value: mysql-34b54408-student-9a28.1.aivencloud.com
      - key: DB_PORT
        value: 27417
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
